export enum CoursesActionTypes {
  FetchCoursesFromApi = '[MyApp] Fetch Courses From Api',
  FetchCoursesSuccess = '[MyApp] Fetch Courses Success',
  FetchCoursesError = '[MyApp] Fetch Courses Error',
  LoadMoreCourses = '[MyApp] Load More Courses',
  LoadMoreCoursesSuccess = '[MyApp] Load More Courses Success',
  LoadMoreCoursesError = '[MyApp] Load More Courses Error',
  SearchCourses = '[MyApp] Search Courses',
  SearchCoursesSuccess = '[MyApp] Search Courses Success',
  SearchCoursesError = '[MyApp] Search Courses Error',
  DeleteCourse = '[MyApp] Delete Course',
  DeleteCourseSuccess = '[MyApp] Delete Course Success',
  DeleteCourseError = '[MyApp] Delete Course Error',
  AddCourse = '[MyApp] Add Course',
  AddCourseSuccess = '[MyApp] Add Course Success',
  AddCourseError = '[MyApp] Add Course Error',
  UpdateCourse = '[MyApp] Update Course',
  UpdateCourseSuccess = '[MyApp] Update Course Success',
  UpdateCourseError = '[MyApp] Update Course Error',
}
